version: '3.8'

services:
  db:
    image: mysql:8.0          # Kita pakai MySQL versi 8 resmi
    container_name: hashico_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Password root database
      MYSQL_DATABASE: hashico_db         # Nama database otomatis dibuat
    ports:
      - "3307:3306"           # PENTING: Mapping Port
    volumes:
      - mysql_data:/var/lib/mysql # Agar data tidak hilang saat docker dimatikan

volumes:
  mysql_data:                 # Menyiapkan tempat penyimpanan data